from userclass import User
from credentials import Credentials

 #_________________________________________USERS____________________________________________________________________

def create_useraccount(user_name, password):
    """
    Creates a new user account.
    """
    new_user = User(user_name, password)
    return new_user

def save_user(user):
    user.save_user()    

def display_user():
    return User.display_user()   

def login_user(user_name, password):
    """
    This function checks if a user exists in the list then allows them to login
    """
    log_user = Credentials.authenticate_user(user_name, password)
    return log_user

 #_________________________________________CREDENTIALS____________________________________________________________________

def create_newcredential(account_type, usr_name, password):
    """
    Function for creating new credential for every usr_name
    """
    new_credential = Credentials(account_type, usr_name, password)
    return new_credential

def retain_credential(credentials):
    """
    Save credentials to the credential list
    """
    credentials.save_credential()

def remove_credential(credentials):
    """
    Delete credentials from the credential list
    """
    credentials.delete_credential()  

def display_credential():
    """
    Display user's credentials in the list
    """
    return Credentials.view_credential()    

def generate_password():
    ran_pass = Credentials.random_password()
    return ran_pass


def password_locker():
    print("Welcome to Password Locker\n Enter the following short codes to select an option\n NA 👶️👶️👶️👶️👶️👶️ Add New Account\n EA 🧓️🧓️🧓️🧓️🧓️🧓️ Existing Account")
    short_code = input("").lower().strip()
    # on entering short code if new user ask for username, then generate password
    # if existing user, ask for password. authenticate and display whether succesful or  return error message
    if short_code == "na":
        print("Enter a username to start...")
        user_name = input("USERNAME: ")
        print("A password will be autogenerated for you.")
        password = generate_password()
        created_user = create_useraccount(user_name, password)
        save_user(created_user)
        print(user_name, password)

if __name__ == '__main__':
    print("Password Locker starting up...")
    password_locker()